import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { DeliveryStatus, ReportStatus, Role } from "@/generated/prisma/enums";
import { myEntries } from "@/lib/db/my-entries";
import { listReports, reportsCsv } from "@/lib/db/report-history";
import type { Actor } from "@/lib/db/scoped";

import { createTenant, raw, resetDatabase } from "./helpers";

/**
 * Reports history and the personal export, against a real Postgres.
 *
 * The delivery filters are the part worth proving. "All delivered" is a claim
 * about a set, and the obvious implementation (`every: DELIVERED`) is true for
 * a report with no deliveries at all — which would show an undelivered report
 * under a green filter, the exact failure the filter exists to prevent.
 */
let a: Awaited<ReturnType<typeof createTenant>>;
let b: Awaited<ReturnType<typeof createTenant>>;
let delivered: string;
let pending: string;
let problem: string;
let never: string;

const actorFor = (
  tenant: Awaited<ReturnType<typeof createTenant>>,
  who: "owner" | "guard",
): Actor => ({
  userId: tenant[who].id,
  companyId: tenant.company.id,
  role: who === "owner" ? Role.OWNER : Role.GUARD,
});

async function makeReport(
  tenant: Awaited<ReturnType<typeof createTenant>>,
  version: number,
  statuses: DeliveryStatus[],
): Promise<string> {
  const shift = await raw.shift.create({
    data: {
      siteId: tenant.site.id,
      guardId: tenant.guard.id,
      clientId: `${tenant.company.slug}-shift-r${version}`,
      scheduledStart: new Date("2026-02-01T06:00:00.000Z"),
      scheduledEnd: new Date("2026-02-01T16:00:00.000Z"),
    },
  });

  const report = await raw.report.create({
    data: {
      shiftId: shift.id,
      version: 1,
      status: ReportStatus.SENT,
      generatedById: tenant.guard.id,
      pages: 3,
      bytes: 120_000,
      generatedAt: new Date("2026-02-01T16:05:00.000Z"),
    },
  });

  for (const [index, status] of statuses.entries()) {
    const recipient = await raw.recipient.create({
      data: {
        siteId: tenant.site.id,
        email: `to-${version}-${index}@client.test`,
        name: `Recipient ${index}`,
        roleLabel: "Operations",
      },
    });
    await raw.reportDelivery.create({
      data: {
        reportId: report.id,
        recipientId: recipient.id,
        email: recipient.email,
        status,
      },
    });
  }

  return report.id;
}

beforeAll(async () => {
  await resetDatabase();
  a = await createTenant("rep-a");
  b = await createTenant("rep-b");

  delivered = await makeReport(a, 1, [
    DeliveryStatus.DELIVERED,
    DeliveryStatus.DELIVERED,
  ]);
  pending = await makeReport(a, 2, [DeliveryStatus.DELIVERED, DeliveryStatus.QUEUED]);
  problem = await makeReport(a, 3, [DeliveryStatus.DELIVERED, DeliveryStatus.BOUNCED]);
  // No deliveries at all. This is the row that breaks a naive `every`.
  never = await makeReport(a, 4, []);
  await makeReport(b, 1, [DeliveryStatus.DELIVERED]);
});

afterAll(async () => {
  await raw.$disconnect();
});

describe("listReports scoping", () => {
  it("never returns another company's report", async () => {
    const { rows, total } = await listReports(actorFor(a, "owner"));
    expect(total).toBe(4);
    const shiftSiteIds = new Set(rows.map((row) => row.siteName));
    expect(shiftSiteIds.has("rep-b site")).toBe(false);
  });

  it("gives a guard only their own reports", async () => {
    // Every report here was generated by that tenant's guard, so the useful
    // control is the opposite direction: a guard from the sibling company
    // must see none of them.
    const { total } = await listReports(actorFor(b, "guard"));
    expect(total).toBe(1);
  });
});

describe("delivery filters", () => {
  it("'delivered' means every delivery landed AND there was at least one", async () => {
    const { rows } = await listReports(actorFor(a, "owner"), {
      delivery: "delivered",
    });
    const ids = rows.map((row) => row.id);
    expect(ids).toContain(delivered);
    expect(ids).not.toContain(pending);
    expect(ids).not.toContain(problem);
    // The one that matters: a report nobody was sent has not been delivered.
    expect(ids).not.toContain(never);
  });

  it("'pending' finds a report still in flight", async () => {
    const { rows } = await listReports(actorFor(a, "owner"), {
      delivery: "pending",
    });
    const ids = rows.map((row) => row.id);
    expect(ids).toContain(pending);
    expect(ids).not.toContain(delivered);
  });

  it("'problem' finds a bounce even when the other copy landed", async () => {
    // A report that reached three of four recipients is a problem, not a
    // success. Filtering on "no delivery succeeded" would miss this entirely.
    const { rows } = await listReports(actorFor(a, "owner"), {
      delivery: "problem",
    });
    const ids = rows.map((row) => row.id);
    expect(ids).toContain(problem);
    expect(ids).not.toContain(delivered);
  });

  it("'any' is not a filter", async () => {
    const { total } = await listReports(actorFor(a, "owner"), {
      delivery: "any",
    });
    expect(total).toBe(4);
  });
});

describe("reportsCsv", () => {
  it("writes a header and one line per report", async () => {
    const { rows } = await listReports(actorFor(a, "owner"));
    const csv = reportsCsv(rows);
    const lines = csv.trimEnd().split("\r\n");
    expect(lines).toHaveLength(rows.length + 1);
    expect(lines[0]).toBe(
      "Generated,Site,Guard,Version,Incidents,Event night,Pages,Bytes,Delivered,In flight,Problems",
    );
  });
});

describe("myEntries", () => {
  it("returns entries from shifts the person worked, and no others", async () => {
    const mine = await raw.entry.create({
      data: {
        shiftId: a.shift.id,
        clientId: "entry-mine",
        type: "NOTE",
        text: "Front lobby clear",
        occurredAt: new Date("2026-02-01T07:00:00.000Z"),
      },
    });
    await raw.entry.create({
      data: {
        shiftId: b.shift.id,
        clientId: "entry-theirs",
        type: "NOTE",
        text: "Someone else's shift",
        occurredAt: new Date("2026-02-01T07:00:00.000Z"),
      },
    });

    const rows = await myEntries(actorFor(a, "guard"));
    const ids = rows.map((row) => row.id);
    expect(ids).toContain(mine.id);
    expect(rows.every((row) => row.text !== "Someone else's shift")).toBe(true);
  });

  it("includes a deleted entry, with its reason", async () => {
    // A guard exporting their own record after a dispute needs the full
    // picture. Dropping soft-deleted rows would make the export a worse
    // record than the app it came from.
    await raw.entry.create({
      data: {
        shiftId: a.shift.id,
        clientId: "entry-deleted",
        type: "NOTE",
        text: "Logged against the wrong gate",
        occurredAt: new Date("2026-02-01T08:00:00.000Z"),
        deletedAt: new Date("2026-02-01T08:05:00.000Z"),
        deleteReason: "duplicate of 08:00",
      },
    });

    const rows = await myEntries(actorFor(a, "guard"));
    const deletedRow = rows.find((row) => row.deletedAt !== null);
    expect(deletedRow).toBeDefined();
    expect(deletedRow?.deletedReason).toBe("duplicate of 08:00");
  });
});
