import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`; not ours to lint.
    "src/generated/**",
  ]),
  {
    // Section 17 requires company isolation in a single data-access layer.
    // A convention would not survive thirteen milestones, so the rule is
    // enforced here: reaching for Prisma outside `lib/db` fails the build.
    //
    // Scoped to `src/**` because that is everything that ships. `lib/db/**` is
    // the implementation and is exempt; `prisma/seed.ts` and `tests/db/**` are
    // outside `src` and hold raw clients on purpose — a test that proves the
    // scoped layer denies a read has to write the denied row around the layer.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/db/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/lib/db/client",
              message:
                "Import `db` from '@/lib/db/scoped' instead. Raw Prisma access bypasses company scoping (section 17).",
            },
            {
              name: "@/generated/prisma/client",
              message:
                "Import `db` from '@/lib/db/scoped' instead. Raw Prisma access bypasses company scoping (section 17).",
            },
          ],
          patterns: [
            {
              group: ["**/generated/prisma/client", "**/lib/db/client"],
              message:
                "Import `db` from '@/lib/db/scoped' instead. Raw Prisma access bypasses company scoping (section 17).",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
