import * as React from "react";

import { Document, Page, Text, View } from "@react-pdf/renderer";
import { renderToBuffer } from "@react-pdf/renderer";

import type { ReceiptData } from "@/lib/db/receipt";
import { formatDateTimeArchival } from "@/lib/time";
import { COLORS, registerFonts, styles } from "./theme";

/**
 * Section 9.5's "Download receipt PDF": one page, the same facts as the screen.
 *
 * It exists because the screen is not filable. A property manager who needs to
 * show an insurer that a report went out on the night in question cannot
 * attach a URL to a claim; they attach a PDF. So the receipt has to leave the
 * app as a document.
 *
 * Deliberately not a page inside the report itself. The report is the evidence
 * about the shift; the receipt is evidence about the report, and binding them
 * into one file would mean regenerating the report every time a delivery state
 * changed — which is to say, changing the evidence after a bounce.
 */

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={{ flexDirection: "row", marginBottom: 6 }}>
      <Text style={{ width: 130, color: COLORS.muted, fontSize: 9 }}>{label}</Text>
      <Text style={{ flex: 1, fontSize: 9 }}>{value}</Text>
    </View>
  );
}

export function ReceiptDocument({ data }: { data: ReceiptData }) {
  const zone = data.siteTimezone;
  const at = (when: Date | null) => (when ? formatDateTimeArchival(when, zone) : "—");

  return (
    <Document
      title={`Delivery receipt — ${data.siteName} v${data.version}`}
      author={data.companyName}
      creator="Transient"
      producer="Transient"
    >
      <Page size="LETTER" style={styles.page}>
        <Text style={{ fontSize: 16, marginBottom: 2 }}>Delivery receipt</Text>
        <Text style={{ fontSize: 10, color: COLORS.muted, marginBottom: 14 }}>
          {data.companyName} · {data.siteName} · report v{data.version}
        </Text>

        <View style={{ marginBottom: 14 }}>
          <Row label="Guard on shift" value={data.guardName} />
          <Row label="Shift" value={`${at(data.shiftStart)} → ${at(data.shiftEnd)}`} />
          <Row label="Report generated by" value={data.generatedByName} />
          <Row label="Generated at" value={at(data.generatedAt)} />
          <Row label="Sent at" value={at(data.sentAt)} />
          <Row
            label="Pages / size"
            value={`${data.pages ?? "—"} pages · ${
              data.bytes === null ? "—" : `${(data.bytes / 1024).toFixed(0)} KB`
            }`}
          />
        </View>

        <Text style={{ fontSize: 11, marginBottom: 6 }}>Recipients</Text>
        {data.deliveries.length === 0 ? (
          <Text style={{ fontSize: 9, color: COLORS.muted, marginBottom: 14 }}>
            This report was not sent.
          </Text>
        ) : (
          <View style={{ marginBottom: 14 }}>
            {data.deliveries.map((delivery) => (
              <View
                key={delivery.id}
                style={{
                  borderBottomWidth: 0.5,
                  borderBottomColor: COLORS.rule,
                  paddingBottom: 5,
                  marginBottom: 5,
                }}
              >
                <Text style={{ fontSize: 9 }}>
                  {delivery.name ? `${delivery.name} · ` : ""}
                  {delivery.email}
                  {delivery.required ? " · required" : ""}
                </Text>
                <Text style={{ fontSize: 8, color: COLORS.muted }}>
                  {delivery.status} at {at(delivery.statusAt)}
                  {delivery.providerMessageId
                    ? ` · message ${delivery.providerMessageId}`
                    : ""}
                </Text>
                {delivery.bounceReason ? (
                  <Text style={{ fontSize: 8, color: COLORS.muted }}>
                    Reason: {delivery.bounceReason}
                  </Text>
                ) : null}
              </View>
            ))}
          </View>
        )}

        <Text style={{ fontSize: 11, marginBottom: 6 }}>Integrity</Text>
        <Row label="File SHA-256" value={data.sha256 ?? "—"} />
        <Row label="Content hash" value={data.contentHash ?? "—"} />

        <Text
          style={{
            fontSize: 7,
            color: COLORS.muted,
            marginTop: 16,
            lineHeight: 1.4,
          }}
        >
          The content hash covers the shift&apos;s recorded facts rather than the PDF
          file, so this page can be checked against the database after the file has been
          copied or re-saved. Delivery states are those known at the moment this receipt
          was produced; a later bounce or complaint will appear on the live receipt and
          not on this copy.
        </Text>
        <Text style={{ fontSize: 7, color: COLORS.muted, marginTop: 6 }}>
          Produced {formatDateTimeArchival(new Date(), zone)} · report {data.reportId}
        </Text>
      </Page>
    </Document>
  );
}

export async function renderReceipt(data: ReceiptData): Promise<Buffer> {
  registerFonts();
  return renderToBuffer(<ReceiptDocument data={data} />);
}
